/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by `next dev`/`next build`. It is
// committed here only so `tsc` has something to reference before the
// first run; Next.js will overwrite it automatically.
